### ISSUE TITLE
Site appears to be empty, or down

### ISSUE THREAD

**Issue by RichardLitt** [AgilionApps/site#1]
If this is the same as https://agilion.com/. It's only an image, at the moment. 

Let me know if you want help.

**Comment by adambouchard** [comment]
Thank you @RichardLitt for opening this issue and offering to help.  :)

I had removed the content a while ago to focus on some other things.  I recently came back to review and update the site.

I was curious and checked out your profile and learned about this https://birdinginvermont.com/ you created. Very cool!

**Comment by RichardLitt** [comment]
Thanks! No worries - I was just checking who else is coding in the area. Birding in Vermont is fun. :)
